---
name: ci

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef Workstation
        run: . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chef-workstation
        shell: powershell
      - name: Verify Inspec Profile
        run: C:\opscode\chef-workstation\bin\inspec check .
        shell: powershell
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Run Inspec Test
        run: C:\opscode\chef-workstation\bin\inspec exec .
        shell: powershell
        continue-on-error: true
        env:
          CHEF_LICENSE: accept-no-persist
